// Fallback Mock & Offline Engine for Valparai Rental Cars
// Ensures the live Vercel frontend always displays all vehicles, bookings, and portals even when backend API is offline.

export const INITIAL_VEHICLES = [
  {
    id: 'veh_etios',
    vehicle_name: 'Toyota Etios Platinum',
    brand: 'Toyota',
    model: 'Etios',
    category: 'Sedan',
    registration_number: 'TN 41 AX 4201',
    image: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80',
    seats: 5,
    fuel_type: 'Petrol',
    transmission: 'Manual',
    price_per_day: 1400,
    availability_status: 'available',
    description: 'Highly reliable sedan with supreme fuel efficiency and smooth hill climbing torque. Ideal for couple and small family tours in Valparai.',
    mileage: 24500,
    is_available_for_dates: true
  },
  {
    id: 'veh_thar',
    vehicle_name: 'Mahindra Thar 4x4 Hardtop',
    brand: 'Mahindra',
    model: 'Thar',
    category: 'SUV',
    registration_number: 'TN 38 BX 9901',
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80',
    seats: 4,
    fuel_type: 'Diesel',
    transmission: 'Manual',
    price_per_day: 3800,
    availability_status: 'available',
    description: 'Legendary off-roader built for tea plantation gravel trails, high-altitude viewpoints, and mist-laden forest hairpins.',
    mileage: 18200,
    is_available_for_dates: true
  },
  {
    id: 'veh_innova',
    vehicle_name: 'Toyota Innova Crysta ZX',
    brand: 'Toyota',
    model: 'Innova Crysta',
    category: 'MUV',
    registration_number: 'TN 41 CZ 5520',
    image: 'https://images.unsplash.com/photo-1503376780353-7e6692767b70?auto=format&fit=crop&w=800&q=80',
    seats: 7,
    fuel_type: 'Diesel',
    transmission: 'Automatic',
    price_per_day: 3200,
    availability_status: 'available',
    description: 'The undisputed monarch of mountain highways. Unrivaled ride comfort, plush rear AC, and massive boot space for extended Valparai stays.',
    mileage: 31000,
    is_available_for_dates: true
  },
  {
    id: 'veh_creta',
    vehicle_name: 'Hyundai Creta SX Turbo',
    brand: 'Hyundai',
    model: 'Creta',
    category: 'SUV',
    registration_number: 'TN 38 DK 7741',
    image: 'https://images.unsplash.com/photo-1502877338535-766e1452684a?auto=format&fit=crop&w=800&q=80',
    seats: 5,
    fuel_type: 'Petrol',
    transmission: 'Automatic',
    price_per_day: 2600,
    availability_status: 'available',
    description: 'Panoramic sunroof opens up the lush Western Ghats canopy. Features hill assist, cruise control, and effortless paddle shifters.',
    mileage: 14000,
    is_available_for_dates: true
  },
  {
    id: 'veh_swift',
    vehicle_name: 'Maruti Suzuki Swift ZXi',
    brand: 'Maruti Suzuki',
    model: 'Swift',
    category: 'Hatchback',
    registration_number: 'TN 41 EM 1089',
    image: 'https://images.unsplash.com/photo-1552519507-da3b142c6e3d?auto=format&fit=crop&w=800&q=80',
    seats: 5,
    fuel_type: 'Petrol',
    transmission: 'Manual',
    price_per_day: 1200,
    availability_status: 'available',
    description: 'Compact, agile, and wonderfully easy to park near scenic roadside waterfalls and tea stalls across Valparai.',
    mileage: 22000,
    is_available_for_dates: true
  },
  {
    id: 'veh_scorpio',
    vehicle_name: 'Mahindra Scorpio-N Z8',
    brand: 'Mahindra',
    model: 'Scorpio-N',
    category: 'SUV',
    registration_number: 'TN 38 FA 3302',
    image: 'https://images.unsplash.com/photo-1519641471654-76ce0107ad1b?auto=format&fit=crop&w=800&q=80',
    seats: 7,
    fuel_type: 'Diesel',
    transmission: 'Automatic',
    price_per_day: 3400,
    availability_status: 'available',
    description: 'High muscular stance, commanding visibility over hairpin curves, and heavy-duty suspension for uneven mountain terrain.',
    mileage: 16500,
    is_available_for_dates: true
  },
  {
    id: 'veh_city',
    vehicle_name: 'Honda City ZX i-VTEC',
    brand: 'Honda',
    model: 'City',
    category: 'Sedan',
    registration_number: 'TN 41 GB 6614',
    image: 'https://images.unsplash.com/photo-1617814076367-b759c7d7e738?auto=format&fit=crop&w=800&q=80',
    seats: 5,
    fuel_type: 'Petrol',
    transmission: 'Automatic',
    price_per_day: 2400,
    availability_status: 'available',
    description: 'Aerodynamic elegance, serene cabin insulation, and supple suspension delivering effortless gliding on winding roads.',
    mileage: 19800,
    is_available_for_dates: true
  },
  {
    id: 'veh_nexon_ev',
    vehicle_name: 'Tata Nexon.ev Max',
    brand: 'Tata',
    model: 'Nexon EV',
    category: 'SUV',
    registration_number: 'TN 38 EV 0055',
    image: 'https://images.unsplash.com/photo-1563720223185-11003d516935?auto=format&fit=crop&w=800&q=80',
    seats: 5,
    fuel_type: 'Electric',
    transmission: 'Automatic',
    price_per_day: 2800,
    availability_status: 'available',
    description: 'Zero tailpipe emissions to keep Valparai rain forests pristine. Instant electric torque for quiet, thrilling hill climbs.',
    mileage: 9500,
    is_available_for_dates: true
  },
  {
    id: 'veh_ertiga',
    vehicle_name: 'Maruti Suzuki Ertiga Smart Hybrid',
    brand: 'Maruti Suzuki',
    model: 'Ertiga',
    category: 'MUV',
    registration_number: 'TN 41 HJ 9021',
    image: 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=800&q=80',
    seats: 7,
    fuel_type: 'Petrol',
    transmission: 'Manual',
    price_per_day: 2200,
    availability_status: 'maintenance',
    description: 'Popular 7-seater currently undergoing periodic brake-pad inspection by our workshop team.',
    mileage: 38000,
    is_available_for_dates: false
  }
];

export const INITIAL_BOOKINGS = [
  {
    id: 'VRC-2026-081',
    customer_id: 'cust_01',
    customer_name: 'Karthikeyan R',
    customer_email: 'customer@valparai.com',
    customer_phone: '+91 94424 10020',
    vehicle_id: 'veh_etios',
    vehicle_name: 'Toyota Etios Platinum',
    brand: 'Toyota',
    image: 'https://images.unsplash.com/photo-1549399542-7e3f8b79c341?auto=format&fit=crop&w=800&q=80',
    pickup_location: 'Valparai Town Stand',
    pickup_date: '2026-10-01',
    return_date: '2026-10-04',
    number_of_days: 3,
    total_amount: 4200,
    booking_status: 'completed',
    payment_status: 'paid',
    payment_method: 'UPI',
    created_at: '2026-09-28T10:00:00.000Z',
    user_rating: 5,
    user_feedback: 'Smooth drive through all 40 hairpin curves. Highly recommended!'
  }
];

export const INITIAL_MAINTENANCE = [
  {
    id: 'mnt_01',
    vehicle_id: 'veh_ertiga',
    vehicle_name: 'Maruti Suzuki Ertiga Smart Hybrid',
    brand: 'Maruti Suzuki',
    registration_number: 'TN 41 HJ 9021',
    image: 'https://images.unsplash.com/photo-1541899481282-d53bffe3c35d?auto=format&fit=crop&w=800&q=80',
    mechanic_id: 'mech_01',
    mechanic_name: 'Muthu Vel (Hill Specialist)',
    issue: 'Ghat road brake pad check & coolant replacement',
    service_description: 'Replacing front disc pads and top-up engine radiator coolant for steep hill climbs.',
    service_cost: 2400,
    maintenance_status: 'In Progress',
    priority: 'Urgent',
    scheduled_date: '2026-09-29',
    completed_date: null
  },
  {
    id: 'mnt_02',
    vehicle_id: 'veh_thar',
    vehicle_name: 'Mahindra Thar 4x4 Hardtop',
    brand: 'Mahindra',
    registration_number: 'TN 38 BX 9901',
    image: 'https://images.unsplash.com/photo-1533473359331-0135ef1b58bf?auto=format&fit=crop&w=800&q=80',
    mechanic_id: 'mech_01',
    mechanic_name: 'Muthu Vel (Hill Specialist)',
    issue: '4x4 Transfer Case fluid inspection',
    service_description: 'Completed 4WD transfer case inspection and differential oil top-up.',
    service_cost: 1800,
    maintenance_status: 'Completed',
    priority: 'Normal',
    scheduled_date: '2026-09-27',
    completed_date: '2026-09-28'
  }
];

export const INITIAL_FEEDBACK = [
  {
    id: 'fb_01',
    customer_name: 'Priya Sundaram',
    vehicle_name: 'Toyota Innova Crysta ZX',
    rating: 5,
    comments: 'Superb vehicle for Valparai ghat road! Clean interiors and zero issues with AC or brakes on steep curves.',
    created_at: '2026-09-28T14:30:00.000Z'
  },
  {
    id: 'fb_02',
    customer_name: 'Rajesh Kannan',
    vehicle_name: 'Mahindra Thar 4x4 Hardtop',
    rating: 5,
    comments: 'Took the Thar into tea estate rocky viewpoints. Unbelievable comfort and power!',
    created_at: '2026-09-27T18:00:00.000Z'
  }
];
